package com.auctionhub.server.service;

import com.auctionhub.common.model.Auction;
import com.auctionhub.common.model.AutoBidConfig;
import com.auctionhub.common.model.BidTransaction;
import com.auctionhub.common.strategy.AuctionExtensionStrategy;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

public class AutoBidEngine {
    private final AuctionExtensionStrategy extensionStrategy;

    public AutoBidEngine(AuctionExtensionStrategy extensionStrategy) {
        this.extensionStrategy = extensionStrategy;
    }

    public BidComputationResult applyManualBid(Auction auction,
                                               List<AutoBidConfig> configs,
                                               UUID bidderId,
                                               BigDecimal amount,
                                               LocalDateTime bidTime) {
        List<BidTransaction> generatedBids = new ArrayList<>();
        applyBid(auction, generatedBids, bidderId, amount, false, bidTime, "Bid trực tiếp");
        resolveAutoBids(auction, configs, generatedBids, bidTime);
        extendIfNeeded(auction, bidTime);
        return new BidComputationResult(auction, generatedBids);
    }

    public BidComputationResult applyAutoBidRegistration(Auction auction,
                                                         List<AutoBidConfig> configs,
                                                         LocalDateTime bidTime) {
        List<BidTransaction> generatedBids = new ArrayList<>();
        resolveAutoBids(auction, configs, generatedBids, bidTime);
        extendIfNeeded(auction, bidTime);
        return new BidComputationResult(auction, generatedBids);
    }

    private void resolveAutoBids(Auction auction,
                                 List<AutoBidConfig> configs,
                                 List<BidTransaction> generatedBids,
                                 LocalDateTime bidTime) {
        List<AutoBidConfig> activeConfigs = configs.stream()
                .filter(AutoBidConfig::isEnabled)
                .sorted(Comparator.comparing(AutoBidConfig::getCreatedAt))
                .toList();

        boolean changed;
        do {
            changed = false;
            for (AutoBidConfig config : activeConfigs) {
                if (Objects.equals(config.getBidderId(), auction.getLeadingBidderId())) {
                    continue;
                }
                BigDecimal step = config.getIncrementAmount();
                BigDecimal nextAmount = auction.getCurrentPrice().add(step);
                if (config.getMaxBid().compareTo(nextAmount) >= 0) {
                    applyBid(auction, generatedBids, config.getBidderId(), nextAmount, true, bidTime,
                            "Auto-bid tăng theo cấu hình");
                    changed = true;
                } else if (config.getMaxBid().compareTo(auction.getCurrentPrice()) > 0) {
                    applyBid(auction, generatedBids, config.getBidderId(), config.getMaxBid(), true, bidTime,
                            "Auto-bid dùng mức trần cuối cùng");
                    changed = true;
                }
            }
        } while (changed);
    }

    private void applyBid(Auction auction,
                          List<BidTransaction> generatedBids,
                          UUID bidderId,
                          BigDecimal amount,
                          boolean autoGenerated,
                          LocalDateTime bidTime,
                          String note) {
        auction.setCurrentPrice(amount);
        auction.setLeadingBidderId(bidderId);
        auction.touch();
        generatedBids.add(new BidTransaction(UUID.randomUUID(), bidTime, bidTime, auction.getId(), bidderId, amount, autoGenerated, note));
    }

    private void extendIfNeeded(Auction auction, LocalDateTime bidTime) {
        if (extensionStrategy.shouldExtend(auction, bidTime)) {
            auction.setEndTime(extensionStrategy.extendTo(auction, bidTime));
        }
    }

    public record BidComputationResult(Auction auction, List<BidTransaction> generatedBids) {
    }
}
