package com.auctionhub.server.dao.jdbc;

import com.auctionhub.common.model.BidTransaction;
import com.auctionhub.server.dao.BidDao;
import com.auctionhub.server.db.DatabaseManager;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class JdbcBidDao implements BidDao {
    private final DatabaseManager databaseManager;

    public JdbcBidDao(DatabaseManager databaseManager) {
        this.databaseManager = databaseManager;
    }

    @Override
    public BidTransaction save(BidTransaction bidTransaction) {
        String sql = """
                INSERT INTO bids (id, auction_id, bidder_id, amount, auto_generated, note, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                """;
        try (var connection = databaseManager.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {
            bind(statement, bidTransaction);
            statement.executeUpdate();
            return bidTransaction;
        } catch (SQLException ex) {
            throw new IllegalStateException("Không thể lưu bid", ex);
        }
    }

    @Override
    public void saveAll(List<BidTransaction> bidTransactions) {
        for (BidTransaction bidTransaction : bidTransactions) {
            save(bidTransaction);
        }
    }

    @Override
    public List<BidTransaction> findByAuctionId(UUID auctionId) {
        String sql = "SELECT * FROM bids WHERE auction_id = ? ORDER BY created_at ASC";
        try (var connection = databaseManager.getConnection();
             PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, auctionId.toString());
            try (ResultSet resultSet = statement.executeQuery()) {
                List<BidTransaction> bids = new ArrayList<>();
                while (resultSet.next()) {
                    bids.add(mapRow(resultSet));
                }
                return bids;
            }
        } catch (SQLException ex) {
            throw new IllegalStateException("Không thể truy vấn bids", ex);
        }
    }

    private void bind(PreparedStatement statement, BidTransaction bidTransaction) throws SQLException {
        statement.setString(1, bidTransaction.getId().toString());
        statement.setString(2, bidTransaction.getAuctionId().toString());
        statement.setString(3, bidTransaction.getBidderId().toString());
        statement.setBigDecimal(4, bidTransaction.getAmount());
        statement.setBoolean(5, bidTransaction.isAutoGenerated());
        statement.setString(6, bidTransaction.getNote());
        statement.setObject(7, bidTransaction.getCreatedAt());
        statement.setObject(8, bidTransaction.getUpdatedAt());
    }

    private BidTransaction mapRow(ResultSet resultSet) throws SQLException {
        return new BidTransaction(
                UUID.fromString(resultSet.getString("id")),
                resultSet.getTimestamp("created_at").toLocalDateTime(),
                resultSet.getTimestamp("updated_at").toLocalDateTime(),
                UUID.fromString(resultSet.getString("auction_id")),
                UUID.fromString(resultSet.getString("bidder_id")),
                resultSet.getBigDecimal("amount"),
                resultSet.getBoolean("auto_generated"),
                resultSet.getString("note")
        );
    }
}
