auction.db.url=jdbc:mysql://localhost:3306/auction_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
auction.db.user=root
auction.db.password=230607
auction.server.port=9090
auction.admin.key=admin-2026