# --- CH?N LO?I DATABASE ---
app.db.vendor=mysql

# --- ??A CH? K?T N?I (URL) ---
# Tr? ??n Host c?a Aiven, Port 27155 và Database tên là auction_db
app.db.mysql.url=jdbc:mysql://mysql-auction-db-auction-database.g.aivencloud.com:27155/auction_db?useSSL=true&serverTimezone=UTC

# --- TÀI KHO?N ??NG NH?P ---
app.db.mysql.username=avnadmin
app.db.mysql.password=AVNS_iN6bJdUFjz5GV-dQXd-