
app.db.vendor=mysql

# Connect to Aiven Cloud - Port 27155 - DB: auction_db
app.db.mysql.url=jdbc:mysql://mysql-auction-db-auction-database.g.aivencloud.com:27155/auction_db?useSSL=true&serverTimezone=UTC

# TAI KHOAN DANG NHAP
app.db.mysql.username=avnadmin
app.db.mysql.password=AVNS_iN6bJdUFjz5GV-dQXd-
