app.db.vendor=mysql

# Connect to Localhost
app.db.mysql.url=jdbc:mysql://127.0.0.1:3306/auction_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC


app.db.mysql.username=root
app.db.mysql.password=vubinhle14032007@