package com.auctionapp.auctionappjava.common.dto;

import java.io.Serializable;
import java.math.BigDecimal;

public record BidRankingResponse(
    int rank, String bidderName, BigDecimal amount, String bidTime, boolean autoGenerated)
    implements Serializable {}
