package com.auctionapp.auctionappjava.server.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

// mỗi lần user đặt giá = 1 record BidTransaction
public class BidTransaction extends BaseEntity {
  private UUID auctionId;
  private UUID bidderId;
  private BigDecimal amount;
  private boolean autoGenerated;
  private String note;

  public BidTransaction() {
    super();
  }

  public BidTransaction(
      UUID id,
      LocalDateTime createdAt,
      LocalDateTime updatedAt,
      UUID auctionId,
      UUID bidderId,
      BigDecimal amount,
      boolean autoGenerated,
      String note) {
    super(id, createdAt, updatedAt);
    this.auctionId = auctionId;
    this.bidderId = bidderId;
    this.amount = amount;
    this.autoGenerated = autoGenerated;
    this.note = note;
  }

  public UUID getAuctionId() {
    return auctionId;
  }

  public void setAuctionId(UUID auctionId) {
    this.auctionId = auctionId;
  }

  public UUID getBidderId() {
    return bidderId;
  }

  public void setBidderId(UUID bidderId) {
    this.bidderId = bidderId;
  }

  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }

  public boolean isAutoGenerated() {
    return autoGenerated;
  }

  public void setAutoGenerated(boolean autoGenerated) {
    this.autoGenerated = autoGenerated;
  }

  public String getNote() {
    return note;
  }

  public void setNote(String note) {
    this.note = note;
  }
}
