package com.auctionapp.auctionappjava.server.service;

import com.auctionapp.auctionappjava.common.exception.ValidationException;
import com.auctionapp.auctionappjava.common.model.*;
import com.auctionapp.auctionappjava.server.dao.*;

import java.math.BigDecimal;
import java.util.*;

public class AutoBidEngine {
    private final AutoBidDao autoBidDao;
    private final BidDao bidDao;
    private final AuctionDao auctionDao;
    private final UserDao userDao;
    private final WalletService walletService;
    private final BidValidationService bidValidationService;

    public AutoBidEngine(AutoBidDao autoBidDao, BidDao bidDao, AuctionDao auctionDao, UserDao userDao, WalletService walletService, BidValidationService bidValidationService) {
        this.autoBidDao = autoBidDao;
        this.bidDao = bidDao;
        this.auctionDao = auctionDao;
        this.userDao = userDao;
        this.walletService = walletService;
        this.bidValidationService = bidValidationService;
    }

    public AutoBidConfig configure(Auction auction, AutoBidConfig config) {
        bidValidationService.validateAutoBid(auction, config);
        autoBidDao.upsert(config);
        return autoBidDao.findByAuctionAndBidder(config.getAuctionId(), config.getBidderId()).orElse(config);
    }

    public List<BidTransaction> reactToBid(UUID auctionId) {
        List<BidTransaction> made = new ArrayList<>();
        int max = Math.max(5, autoBidDao.findEnabledByAuctionId(auctionId).size() * 3 + 2);
        Set<UUID> noMoney = new HashSet<>();
        for (int i = 0; i < max; i++) {
            Auction a = auctionDao.findById(auctionId).orElseThrow(() -> new ValidationException("Không tìm thấy auction"));
            BigDecimal min = a.getCurrentPrice().add(a.getMinimumIncrement());
            Optional<AutoBidConfig> cand = autoBidDao.findEnabledByAuctionId(auctionId).stream().filter(c -> !c.getBidderId().equals(a.getLeadingBidderId())).filter(c -> !noMoney.contains(c.getBidderId())).filter(c -> c.getMaxBid().compareTo(min) >= 0).filter(c -> eligible(a, c.getBidderId())).min(Comparator.comparing(AutoBidConfig::getCreatedAt));
            if (cand.isEmpty()) break;
            AutoBidConfig c = cand.get();
            BigDecimal amount = a.getCurrentPrice().add(c.getIncrementAmount().max(a.getMinimumIncrement()));
            if (amount.compareTo(c.getMaxBid()) > 0) amount = c.getMaxBid();
            if (amount.compareTo(min) < 0) {
                autoBidDao.setEnabled(c.getAuctionId(), c.getBidderId(), false);
                continue;
            }
            BigDecimal need = c.getBidderId().equals(a.getLeadingBidderId()) ? amount.subtract(a.getCurrentPrice()) : amount;
            if (need.compareTo(BigDecimal.ZERO) > 0 && !walletService.hasSufficientBalance(c.getBidderId(), need)) {
                noMoney.add(c.getBidderId());
                continue;
            }
            made.add(applyBid(a, c.getBidderId(), amount));
        }
        return made;
    }

    private boolean eligible(Auction a, UUID bidderId) {
        return !bidderId.equals(a.getSellerId()) && userDao.findById(bidderId).filter(u -> u.isActive() && u.getRole().isBidder()).isPresent();
    }

    private BidTransaction applyBid(Auction a, UUID bidderId, BigDecimal amount) {
        UUID prev = a.getLeadingBidderId();
        BigDecimal prevPrice = a.getCurrentPrice();
        if (prev != null && prev.equals(bidderId)) {
            BigDecimal delta = amount.subtract(prevPrice);
            if (delta.compareTo(BigDecimal.ZERO) > 0) walletService.debit(bidderId, delta);
        } else {
            walletService.debit(bidderId, amount);
            if (prev != null && prevPrice.compareTo(BigDecimal.ZERO) > 0) walletService.credit(prev, prevPrice);
        }
        BidTransaction b = new BidTransaction();
        b.setAuctionId(a.getId());
        b.setBidderId(bidderId);
        b.setAmount(amount);
        b.setAutoGenerated(true);
        b.setNote("AUTO_BID");
        bidDao.save(b);
        a.setCurrentPrice(amount);
        a.setLeadingBidderId(bidderId);
        auctionDao.update(a);
        return b;
    }
}
