package com.auctionapp.auctionappjava.server.service;

import com.auctionapp.auctionappjava.common.dto.BidHistoryChartResponse;
import com.auctionapp.auctionappjava.common.dto.BidHistoryPointDto;
import com.auctionapp.auctionappjava.common.dto.Response;
import com.auctionapp.auctionappjava.common.model.BidTransaction;
import com.auctionapp.auctionappjava.common.model.User;
import com.auctionapp.auctionappjava.server.dao.AuctionDao;
import com.auctionapp.auctionappjava.server.dao.BidDao;
import com.auctionapp.auctionappjava.server.dao.UserDao;
import com.auctionapp.auctionappjava.server.dao.jdbc.JdbcAuctionDao;
import com.auctionapp.auctionappjava.server.dao.jdbc.JdbcBidDao;
import com.auctionapp.auctionappjava.server.dao.jdbc.JdbcUserDao;

import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

public class BidHistoryService {
    private final AuctionDao auctionDao;
    private final BidDao bidDao;
    private final UserDao userDao;

    public BidHistoryService() {
        this(new JdbcAuctionDao(), new JdbcBidDao(), new JdbcUserDao());
    }

    public BidHistoryService(AuctionDao auctionDao, BidDao bidDao, UserDao userDao) {
        this.auctionDao = auctionDao;
        this.bidDao = bidDao;
        this.userDao = userDao;
    }

    public Response handleGetBidHistory(Object payload) {
        try {
            UUID auctionId = parseAuctionId(payload);
            if (auctionId == null) {
                return new Response(false, "auctionId không hợp lệ.", null);
            }
            if (auctionDao.findById(auctionId).isEmpty()) {
                return new Response(false, "Phiên đấu giá không tồn tại.", null);
            }

            List<BidHistoryPointDto> points = bidDao.findByAuctionId(auctionId).stream()
                    .sorted(Comparator.comparing(BidTransaction::getCreatedAt))
                    .map(this::toPoint)
                    .toList();

            return new Response(true, "Tải lịch sử bid thành công.", new BidHistoryChartResponse(auctionId, points));
        } catch (Exception e) {
            e.printStackTrace();
            return new Response(false, "Lỗi máy chủ khi lấy lịch sử bid: " + e.getMessage(), null);
        }
    }

    private BidHistoryPointDto toPoint(BidTransaction bid) {
        String bidderName = userDao.findById(bid.getBidderId())
                .map(User::getFullName)
                .orElse("Không rõ");
        return new BidHistoryPointDto(
                bid.getId(),
                bid.getAuctionId(),
                bid.getBidderId(),
                bidderName,
                bid.getAmount(),
                bid.getCreatedAt(),
                bid.isAutoGenerated()
        );
    }

    private UUID parseAuctionId(Object payload) {
        if (payload instanceof UUID uuid) return uuid;
        if (payload instanceof String text) return UUID.fromString(text);
        return null;
    }
}
