package com.auctionapp.auctionappjava.server.dao.jdbc;

import com.auctionapp.auctionappjava.common.model.BidTransaction;
import com.auctionapp.auctionappjava.server.dao.BidDao;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

public class JdbcBidDao extends JdbcDaoSupport implements BidDao {
    @Override
    public BidTransaction save(BidTransaction bidTransaction) {
        String sql = """
                INSERT INTO bids (
                    id, auction_id, bidder_id, amount, auto_generated, note, created_at, updated_at)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                ON DUPLICATE KEY UPDATE
                    auction_id = VALUES(auction_id), bidder_id = VALUES(bidder_id), amount = VALUES(amount),
                    auto_generated = VALUES(auto_generated), note = VALUES(note), updated_at = VALUES(updated_at)
                """;
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, uuid(bidTransaction.getId()));
            statement.setString(2, uuid(bidTransaction.getAuctionId()));
            statement.setString(3, uuid(bidTransaction.getBidderId()));
            statement.setBigDecimal(4, bidTransaction.getAmount());
            statement.setBoolean(5, bidTransaction.isAutoGenerated());
            statement.setString(6, bidTransaction.getNote());
            statement.setTimestamp(7, timestamp(bidTransaction.getCreatedAt()));
            statement.setTimestamp(8, timestamp(bidTransaction.getUpdatedAt()));
            statement.executeUpdate();
            return bidTransaction;
        } catch (SQLException exception) {
            throw new IllegalStateException("Khong luu duoc bid", exception);
        }
    }

    @Override
    public List<BidTransaction> findByAuctionId(UUID auctionId) {
        String sql = "SELECT * FROM bids WHERE auction_id = ? ORDER BY created_at";
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, uuid(auctionId));
            try (ResultSet resultSet = statement.executeQuery()) {
                List<BidTransaction> bids = new ArrayList<>();
                while (resultSet.next()) {
                    bids.add(mapBid(resultSet));
                }
                return bids;
            }
        } catch (SQLException exception) {
            throw new IllegalStateException("Khong doc duoc danh sach bid", exception);
        }
    }

    @Override
    public long countByAuctionId(UUID auctionId) {
        return countBySql("SELECT COUNT(*) FROM bids WHERE auction_id = ?", uuid(auctionId));
    }

    @Override
    public long countByBidderId(UUID bidderId) {
        return countBySql("SELECT COUNT(*) FROM bids WHERE bidder_id = ?", uuid(bidderId));
    }

    @Override
    public void deleteByAuctionId(UUID auctionId) {
        String sql = "DELETE FROM bids WHERE auction_id = ?";
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, uuid(auctionId));
            statement.executeUpdate();
        } catch (SQLException exception) {
            throw new IllegalStateException("Khong xoa duoc bid", exception);
        }
    }

    private long countBySql(String sql, String value) {
        try (Connection connection = connection(); PreparedStatement statement = connection.prepareStatement(sql)) {
            statement.setString(1, value);
            try (ResultSet resultSet = statement.executeQuery()) {
                resultSet.next();
                return resultSet.getLong(1);
            }
        } catch (SQLException exception) {
            throw new IllegalStateException("Khong dem duoc bid", exception);
        }
    }

    private BidTransaction mapBid(ResultSet resultSet) throws SQLException {
        return new BidTransaction(
                uuid(resultSet.getString("id")),
                localDateTime(resultSet.getTimestamp("created_at")),
                localDateTime(resultSet.getTimestamp("updated_at")),
                uuid(resultSet.getString("auction_id")),
                uuid(resultSet.getString("bidder_id")),
                resultSet.getBigDecimal("amount"),
                resultSet.getBoolean("auto_generated"),
                resultSet.getString("note"));
    }
}
