package com.auctionapp.auctionappjava.server.dao.jdbc;

import com.auctionapp.auctionappjava.common.model.BidTransaction;
import com.auctionapp.auctionappjava.server.dao.BidDao;
import com.auctionapp.auctionappjava.server.db.DatabaseManager;

import java.math.BigDecimal;
import java.sql.*;
import java.util.*;

public class JdbcBidDao implements BidDao {
    private final DatabaseManager databaseManager;

    public JdbcBidDao() {
        this(new DatabaseManager());
    }

    public JdbcBidDao(DatabaseManager databaseManager) {
        this.databaseManager = databaseManager;
    }

    @Override
    public void save(BidTransaction b) {
        String sql = "INSERT INTO bids (id,auction_id,bidder_id,amount,auto_generated,note,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)";
        try (Connection c = databaseManager.getConnection(); PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, b.getId().toString());
            ps.setString(2, b.getAuctionId().toString());
            ps.setString(3, b.getBidderId().toString());
            ps.setBigDecimal(4, b.getAmount());
            ps.setBoolean(5, b.isAutoGenerated());
            ps.setString(6, b.getNote());
            ps.setObject(7, b.getCreatedAt());
            ps.setObject(8, b.getUpdatedAt());
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException("Không thể lưu bid", e);
        }
    }

    @Override
    public Optional<BidTransaction> findById(UUID bidId) {
        List<BidTransaction> list = many("SELECT * FROM bids WHERE id=?", bidId.toString());
        return list.isEmpty() ? Optional.empty() : Optional.of(list.get(0));
    }

    @Override
    public List<BidTransaction> findByAuctionId(UUID auctionId) {
        return many("SELECT * FROM bids WHERE auction_id=? ORDER BY created_at ASC", auctionId.toString());
    }

    @Override
    public List<BidTransaction> findByBidderId(UUID bidderId) {
        return many("SELECT * FROM bids WHERE bidder_id=? ORDER BY created_at DESC", bidderId.toString());
    }

    @Override
    public Optional<BidTransaction> findHighestByAuctionId(UUID auctionId) {
        List<BidTransaction> list = many("SELECT * FROM bids WHERE auction_id=? ORDER BY amount DESC, created_at ASC LIMIT 1", auctionId.toString());
        return list.isEmpty() ? Optional.empty() : Optional.of(list.get(0));
    }

    @Override
    public long countByAuctionId(UUID auctionId) {
        return count("SELECT COUNT(*) FROM bids WHERE auction_id=?", auctionId.toString());
    }

    @Override
    public long countByBidderId(UUID bidderId) {
        return count("SELECT COUNT(*) FROM bids WHERE bidder_id=?", bidderId.toString());
    }

    @Override
    public BigDecimal totalBidVolume() {
        try (Connection c = databaseManager.getConnection(); PreparedStatement ps = c.prepareStatement("SELECT COALESCE(SUM(amount),0) FROM bids"); ResultSet rs = ps.executeQuery()) {
            return rs.next() ? rs.getBigDecimal(1) : BigDecimal.ZERO;
        } catch (SQLException e) {
            throw new IllegalStateException("Không thể tính tổng bid", e);
        }
    }

    private long count(String sql, Object... params) {
        try (Connection c = databaseManager.getConnection(); PreparedStatement ps = c.prepareStatement(sql)) {
            for (int i = 0; i < params.length; i++) ps.setObject(i + 1, params[i]);
            try (ResultSet rs = ps.executeQuery()) {
                return rs.next() ? rs.getLong(1) : 0L;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Không thể đếm bid", e);
        }
    }

    private List<BidTransaction> many(String sql, Object... params) {
        try (Connection c = databaseManager.getConnection(); PreparedStatement ps = c.prepareStatement(sql)) {
            for (int i = 0; i < params.length; i++) ps.setObject(i + 1, params[i]);
            try (ResultSet rs = ps.executeQuery()) {
                List<BidTransaction> list = new ArrayList<>();
                while (rs.next()) list.add(map(rs));
                return list;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Không thể tải bid", e);
        }
    }

    private BidTransaction map(ResultSet rs) throws SQLException {
        return new BidTransaction(JdbcSupport.uuid(rs, "id"), JdbcSupport.dateTime(rs, "created_at"), JdbcSupport.dateTime(rs, "updated_at"), JdbcSupport.uuid(rs, "auction_id"), JdbcSupport.uuid(rs, "bidder_id"), rs.getBigDecimal("amount"), rs.getBoolean("auto_generated"), rs.getString("note"));
    }
}
