package com.auctionapp.auctionappjava.server.dao.jdbc;

import com.auctionapp.auctionappjava.common.dto.BidDto;
import com.auctionapp.auctionappjava.common.model.BidTransaction;
import com.auctionapp.auctionappjava.server.dao.BidDao;
import com.auctionapp.auctionappjava.server.db.DatabaseManager;

import java.math.BigDecimal;
import java.sql.*;
import java.util.*;

public class JdbcBidDao implements BidDao {
    private final DatabaseManager db;

    public JdbcBidDao(DatabaseManager db) {
        this.db = db;
    }

    public BidTransaction save(BidTransaction b) {
        try (Connection c = db.getConnection(); PreparedStatement ps = c.prepareStatement("INSERT INTO bids(id,created_at,updated_at,auction_id,bidder_id,amount,auto_generated,note) VALUES(?,?,?,?,?,?,?,?)")) {
            ps.setString(1, b.getId().toString());
            ps.setTimestamp(2, JdbcSupport.ts(b.getCreatedAt()));
            ps.setTimestamp(3, JdbcSupport.ts(b.getUpdatedAt()));
            ps.setString(4, b.getAuctionId().toString());
            ps.setString(5, b.getBidderId().toString());
            ps.setBigDecimal(6, b.getAmount());
            ps.setBoolean(7, b.isAutoGenerated());
            ps.setString(8, b.getNote());
            ps.executeUpdate();
            return b;
        } catch (SQLException e) {
            throw new IllegalStateException(e);
        }
    }

    public List<BidDto> findByAuction(UUID auctionId) {
        String sql = "SELECT b.*,u.username AS bidder_name FROM bids b JOIN users u ON u.id=b.bidder_id WHERE b.auction_id=? ORDER BY b.amount DESC,b.created_at ASC";
        try (Connection c = db.getConnection(); PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, auctionId.toString());
            try (ResultSet rs = ps.executeQuery()) {
                List<BidDto> out = new ArrayList<>();
                while (rs.next())
                    out.add(new BidDto(UUID.fromString(rs.getString("id")), UUID.fromString(rs.getString("auction_id")), UUID.fromString(rs.getString("bidder_id")), rs.getString("bidder_name"), rs.getBigDecimal("amount"), JdbcSupport.ldt(rs.getTimestamp("created_at")), rs.getBoolean("auto_generated"), rs.getString("note")));
                return out;
            }
        } catch (SQLException e) {
            throw new IllegalStateException(e);
        }
    }

    public long countByBidder(UUID id) {
        try (Connection c = db.getConnection(); PreparedStatement ps = c.prepareStatement("SELECT COUNT(*) FROM bids WHERE bidder_id=?")) {
            ps.setString(1, id.toString());
            try (ResultSet rs = ps.executeQuery()) {
                rs.next();
                return rs.getLong(1);
            }
        } catch (SQLException e) {
            throw new IllegalStateException(e);
        }
    }

    public BigDecimal sumAmount() {
        try (Connection c = db.getConnection(); PreparedStatement ps = c.prepareStatement("SELECT COALESCE(SUM(amount),0) FROM bids"); ResultSet rs = ps.executeQuery()) {
            rs.next();
            return rs.getBigDecimal(1);
        } catch (SQLException e) {
            throw new IllegalStateException(e);
        }
    }
}
