package com.auctionhub.common.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

public record BidDto(UUID id,
                     UUID auctionId,
                     UUID bidderId,
                     String bidderName,
                     BigDecimal amount,
                     boolean autoGenerated,
                     LocalDateTime createdAt,
                     String note) implements Serializable {
}
